# 跳过构建在Commit Message中添加 [CI SKIP]
kind: pipeline
name: 打包部署

clone:
  disable: true

steps:
  - name: 下载源代码
    image: docker:git
    commands:
      - echo "### $DRONE_GIT_HTTP_URL -> $DRONE_BRANCH"
      - git clone $DRONE_GIT_HTTP_URL ./
      - git checkout $DRONE_BRANCH

#  - name: 编译源代码
#    image: maven:3.6.0-jdk-8-alpine
#    volumes:
#      - name: package-java
#        path: /package-java
#    commands:
#      - mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V -Pdev --settings /package-java/Maven/settings.xml
#      # - mvn deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V -Pdev --settings /package-java/Maven/settings.xml
#      # - cp -f clever-quartz-server/target/clever-quartz-server-*-SNAPSHOT.jar /package-java

#  - name: 构建Docker镜像
#    image: plugins/docker
#    settings:
#      registry: '192.168.159.136:5000'
#      repo: '192.168.159.136:5000/java-service/drone-java-ci-demo-server'
#      # bip: true
#      insecure: true
#      dockerfile: ./Dockerfile
#      target: dev
#      tags: ['0.0.1-SNAPSHOT']
#      force_tag: true
#      auto_tag: false
#      auto_tag_suffix: ''

#  - name: 启动Docker容器
#    image: appleboy/drone-ssh
#    settings:
#      host: 192.168.159.136
#      port: 22
#      username:
#        from_secret: SshUsername
#      password:
#        from_secret: SshPassword
#      command_timeout: 300
#      script:
#        - echo "------------------< 停止容器 >------------------"
#        - docker stop drone-java-ci-demo-server
#        - echo "------------------< 删除容器 >------------------"
#        - docker rm -v drone-java-ci-demo-server
#        - echo "------------------< 删除旧镜像 >------------------"
#        - docker rmi 192.168.159.136:5000/java-service/drone-java-ci-demo-server:0.0.1-SNAPSHOT
#        - echo "------------------< 拉取新镜像 >------------------"
#        - docker pull 192.168.159.136:5000/java-service/drone-java-ci-demo-server:0.0.1-SNAPSHOT
#        - echo "------------------< 运行新镜像 >------------------"
#        - docker run --name drone-java-ci-demo-server -d -p 28081:28081 -v /opt/logs/java-service:/logs 192.168.159.136:5000/java-service/drone-java-ci-demo-server:0.0.1-SNAPSHOT
#        - exit

  - name: 发送通知
    image: drillster/drone-email
    detach: true
    settings:
      host: smtp.163.com
      port: 25 # 465/994
      username: love520lzw1000003@163.com
      password: li19930611
      from: love520lzw1000003@163.com
      recipients: [ 'lzw1000000@163.com', '1183409807@qq.com' ]
      # recipients_only: true
      subject: '{{repo.fullName}}'
      body: '{{repo.fullName}}'

volumes:
  # Java打包目录
  - name: package-java
    host:
      path: /opt/package/java

# -------------------------------------------------------------------------------------------------------------